adnl: check BL stage before sending commands to SPL
For now pyamlboot does not wait the successful boot of SPL (BL2).
In situation, when BootROM on securebooted device tries to load
unsigned BL2, BL2 can't be executed, but pyamlboot continues executing
and sends BL2-specific commands such as cbw (send_and_handle_cbw()),
leading to error:
```
  [INFO    ]: Running BL2 stage...
  [INFO    ]: Send burnsteps after BL2
  [INFO    ]: Requesting CBW...
  Traceback (most recent call last):
  <...>
    File "pyamlboot/adnl.py", line 275, in run_bl2_stage
      cbw = send_and_handle_cbw(epout, epin)
    File "pyamlboot/adnl.py", line 216, in send_and_handle_cbw
      return CBW(msg)
    File "pyamlboot/adnl.py", line 47, in __init__
      raise RuntimeError('Unexpected CBW magic')
  RuntimeError: Unexpected CBW magic
```
Erroneous CBW magic equals to 'Vari' which is the first four letters
of 'getvar:cbw' command's error reply:
  getvar:cbw FAILED (remote: Variable not implemented)

Patch introduces the boot stage check inside run_bl2_stage() in order
to be sure that SPL has been started by run_bootrom_stage()::boot cmd.

Signed-off-by: Evgeny Bachinin <EABachinin@salutedevices.com>